# Generated by Django 3.1.4 on 2020-12-14 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField(default=None)),
                ('species', models.CharField(max_length=80)),
                ('is_dangerous', models.BooleanField(default=False)),
                ('additional_info', models.CharField(max_length=250)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pets', to='pet_app.animal')),
            ],
        ),
    ]
